-- Smart Log Analyzer Database Schema
-- Drop tables if they exist (for clean re-runs)
DROP TABLE IF EXISTS anomaly_flags CASCADE;
DROP TABLE IF EXISTS logs CASCADE;

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Logs table: stores all ingested log entries
CREATE TABLE logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    timestamp TIMESTAMPTZ NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    severity VARCHAR(50) NOT NULL CHECK (severity IN ('INFO', 'WARNING', 'ERROR', 'CRITICAL', 'DEBUG')),
    source VARCHAR(255) NOT NULL,
    message TEXT,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Anomaly flags table: stores detected anomalies with detection metadata and AI explanations
CREATE TABLE anomaly_flags (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    log_id UUID NOT NULL REFERENCES logs(id) ON DELETE CASCADE,
    anomaly_score DECIMAL(5,2) NOT NULL CHECK (anomaly_score >= 0 AND anomaly_score <= 100),
    detection_reason TEXT NOT NULL,
    detection_algorithm VARCHAR(100) NOT NULL,
    ai_explanation TEXT,
    ai_root_cause TEXT,
    ai_next_steps TEXT,
    flagged_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ai_processed_at TIMESTAMPTZ,
    UNIQUE(log_id) -- One flag per log entry
);

-- Indexes for performance
CREATE INDEX idx_logs_timestamp ON logs(timestamp DESC);
CREATE INDEX idx_logs_severity ON logs(severity);
CREATE INDEX idx_logs_source ON logs(source);
CREATE INDEX idx_logs_event_type ON logs(event_type);
CREATE INDEX idx_logs_created_at ON logs(created_at DESC);

CREATE INDEX idx_anomaly_flags_log_id ON anomaly_flags(log_id);
CREATE INDEX idx_anomaly_flags_flagged_at ON anomaly_flags(flagged_at DESC);
CREATE INDEX idx_anomaly_flags_anomaly_score ON anomaly_flags(anomaly_score DESC);
CREATE INDEX idx_anomaly_flags_ai_processed ON anomaly_flags(ai_processed_at) WHERE ai_processed_at IS NULL;

-- Create a view for easy querying of flagged logs with their anomaly details
CREATE OR REPLACE VIEW flagged_logs_view AS
SELECT 
    l.id,
    l.timestamp,
    l.event_type,
    l.severity,
    l.source,
    l.message,
    l.metadata,
    l.created_at,
    af.anomaly_score,
    af.detection_reason,
    af.detection_algorithm,
    af.ai_explanation,
    af.ai_root_cause,
    af.ai_next_steps,
    af.flagged_at,
    af.ai_processed_at
FROM logs l
INNER JOIN anomaly_flags af ON l.id = af.log_id
ORDER BY l.timestamp DESC;

-- Insert some sample data for testing
INSERT INTO logs (timestamp, event_type, severity, source, message) VALUES
    (NOW() - INTERVAL '10 minutes', 'USER_LOGIN', 'INFO', 'auth-service', 'User john@example.com logged in successfully'),
    (NOW() - INTERVAL '9 minutes', 'DATABASE_QUERY', 'INFO', 'api-service', 'Query executed in 45ms'),
    (NOW() - INTERVAL '8 minutes', 'API_REQUEST', 'INFO', 'api-service', 'GET /api/users returned 200'),
    (NOW() - INTERVAL '7 minutes', 'DATABASE_ERROR', 'ERROR', 'api-service', 'Connection timeout to database'),
    (NOW() - INTERVAL '6 minutes', 'DATABASE_ERROR', 'ERROR', 'api-service', 'Failed to execute query: connection lost'),
    (NOW() - INTERVAL '5 minutes', 'DATABASE_ERROR', 'CRITICAL', 'api-service', 'Database pool exhausted'),
    (NOW() - INTERVAL '4 minutes', 'MEMORY_WARNING', 'WARNING', 'worker-service', 'Memory usage at 85%'),
    (NOW() - INTERVAL '3 minutes', 'DISK_SPACE', 'CRITICAL', 'worker-service', 'Disk space below 5%'),
    (NOW() - INTERVAL '2 minutes', 'USER_LOGIN', 'INFO', 'auth-service', 'User jane@example.com logged in successfully'),
    (NOW() - INTERVAL '1 minute', 'API_REQUEST', 'INFO', 'api-service', 'POST /api/orders returned 201');

COMMENT ON TABLE logs IS 'Stores all ingested log entries with timestamp, severity, source, and optional metadata';
COMMENT ON TABLE anomaly_flags IS 'Stores anomaly detection results and AI-generated explanations for flagged log entries';
COMMENT ON COLUMN logs.severity IS 'Log severity level: INFO, WARNING, ERROR, CRITICAL, DEBUG';
COMMENT ON COLUMN anomaly_flags.anomaly_score IS 'Calculated anomaly score from 0-100, higher means more anomalous';
COMMENT ON COLUMN anomaly_flags.detection_algorithm IS 'Name of the algorithm that detected this anomaly';
COMMENT ON COLUMN anomaly_flags.ai_explanation IS 'Plain-English explanation generated by LLM';
COMMENT ON COLUMN anomaly_flags.ai_root_cause IS 'LLM-suggested likely root cause';
COMMENT ON COLUMN anomaly_flags.ai_next_steps IS 'LLM-suggested recommended actions';
